USSBA/sba-gov-katana

src/client/components/atoms/button/button.jsx
src/client/components/organisms/document-article/document-article.jsx
src/client/components/organisms/event-result/event-result.jsx
src/client/components/organisms/search-box/search-box.jsx
src/client/components/templates/event/event.jsx
test/jest/client/components/organisms/event-result/event-result.test.jsx
test/jest/client/components/organisms/search-box/__snapshots__/search-box.test.jsx.snap

And also for `document-article` and `search-box`

T1-00 Hotfix for /events buttons

---

src/client/components/molecules/sba-modal/sba-modal.jsx
src/client/components/molecules/sba-modal/sba-modal.scss
src/client/components/organisms/modals/leave-sba-modal/leave-sba-modal.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-2003

TA-2003 updated accessibility markup, added esc key listener

---

src/client/components/organisms/office-detail/office-detail.jsx
src/client/components/organisms/office-detail/office-detail.scss

for jira ticket https://us-sba.atlassian.net/browse/TA-1743

TA-1743 added margin to h2 when there is no distance data

---

src/client/components/organisms/primary-search-bar/primary-search-bar.jsx
src/client/components/pages/event-lookup-page/event-lookup-page.jsx
test/jest/client/components/organisms/primary-search-bar/primary-search-bar.test.js
test/jest/client/components/pages/event-lookup-page/event-lookup-page.test.jsx

Deployed to https://amy.ussba.io/events/find/

TA-1988 added search button disable function

---

src/client/components/templates/course/course-content.jsx
src/client/components/templates/course/course.view.jsx
src/client/components/templates/course/course.view.scss
src/client/styles/base/_variables.scss
test/jest/client/components/templates/course/course.view.test.jsx

T1-1405 Add course transcript anchors

---

src/client/components/pages/district-office-page/district-office-page.jsx
src/client/components/pages/root-page.jsx
src/client/components/routes.jsx
src/client/components/templates/district-office/district-office.jsx
test/jest/client/components/pages/district-office-page/district-office-page.test.js

Deployed to brian.ussba.io for testing

TA-2926 added district office page and template

---

src/client/components/templates/district-office/district-office.jsx
src/client/components/templates/district-office/district-office.scss
test/jest/client/components/templates/district-office/district-office.test.js

Example of office with twitter link: https://amy.ussba.io/offices/district/19527/
Example of office without twitter link: https://amy.ussba.io/offices/district/19530/

TA-2911 twitter section for district office

---

src/client/components/templates/district-office/district-office.jsx
src/client/components/templates/district-office/district-office.scss
test/jest/client/components/templates/district-office/district-office.test.js

for jira ticket https://us-sba.atlassian.net/browse/TA-2915
1- Region admin
2- District director
3- District deputy director

Feature ta 2915

---

src/client/components/organisms/header-footer/mini-nav/mini-nav.jsx
src/client/translations.js

Removed login link and references to userId

TA-2504 login link removed

---

src/client/components/pages/blog-category/blog-category-page.jsx
src/client/components/routes.jsx
test/jest/client/components/pages/blog-category/blog-category.test.js

Can be viewed at:
https://amy.ussba.io/blogs/success-stories/
and
https://amy.ussba.io/blogs/success-stories/19527/

TA-2927 success stories page

---

src/client/components/organisms/blog-category-deck/blog-category-deck.jsx
src/client/components/pages/blogs-landing/blogs-landing.jsx
test/jest/client/components/pages/blogs-landing/blogs-landing.test.js

for jira ticket https://us-sba.atlassian.net/browse/TA-3004

TA-3004 added success stories and unit tests

---

src/client/components/atoms/decorative-dash/decorative-dash.jsx
src/client/components/atoms/decorative-dash/decorative-dash.scss
src/client/components/molecules/contact-card/contact-card.scss
src/client/components/molecules/quick-links/quick-links.jsx
test/jest/client/components/molecules/call-to-action/__snapshots__/call-to-action.test.jsx.snap
test/jest/client/components/molecules/card/__snapshots__/card.test.jsx.snap
test/jest/client/components/molecules/quick-links/__snapshots__/quick-links.test.js.snap
test/jest/client/components/molecules/readmore/__snapshots__/readmore.test.jsx.snap
test/jest/client/components/organisms/courses-layout/__snapshots__/courses-layout.test.jsx.snap
test/jest/client/components/organisms/document-article-lookup/__snapshots__/document-article-lookup.test.jsx.snap
test/jest/client/components/pages/blog-category/blog-category.test.js

for jira ticket https://us-sba.atlassian.net/browse/TA-3178

Feature ta 3178 - IE11 Layout Fixes

---

src/client/components/organisms/blog-category-deck/blog-category-deck.jsx
src/client/components/organisms/success-stories/success-stories.jsx
test/jest/client/components/pages/blog-category/blog-category-response-faker.js
test/jest/client/components/pages/blog-category/blog-category.test.js
test/jest/client/components/test-data/district-office-blogs.json

for jira ticket https://us-sba.atlassian.net/browse/TA-3214

TA-3214 blogs landing page featured-image

---

src/client/components/organisms/news-releases/news-releases.jsx
src/client/components/organisms/success-stories/success-stories.jsx
src/client/components/templates/district-office/district-office.jsx
src/client/components/templates/district-office/district-office.scss

available here: https://brian.ussba.io/offices/district/19586/

made styling changes to district office page

---

src/client/components/templates/blog/blog.jsx
src/client/components/templates/blog/blog.scss
test/jest/client/components/pages/blog-page/blog-page.test.js

for jira ticket https://us-sba.atlassian.net/browse/TA-2994

Feature ta 2994

---

src/client/components/molecules/contact-card/contact-card.jsx
test/jest/client/components/molecules/contact-card/contact-card.test.jsx
test/jest/client/components/templates/person/__snapshots__/person.test.jsx.snap

Sample pages to observe the behavior:
https://amy.ussba.io/offices/district/6472/
https://amy.ussba.io/person/

TA-3303 contact card accessible icons

---

src/client/components/organisms/hero/hero.jsx

Deployed in brian's environment. Check at https://brian.ussba.io/offices/district/19586/

Ta 3335 image alt to blank

---

src/client/components/molecules/contact-card/contact-card.jsx
src/client/components/molecules/contact-card/contact-card.scss

for jira ticket https://us-sba.atlassian.net/browse/TA-3338
AC:
can be tested at: https://avery.ussba.io/offices/district/17676/

Feature ta 3338 - Contact card title h tag

---

src/client/components/molecules/author-card/author-card.jsx
src/client/components/molecules/author-card/author-card.scss

Deployed to https://brian.ussba.io/offices/district/19586/

Ta 3346 person readmore accessibility

---

src/client/components/organisms/hero/hero.jsx
src/client/components/organisms/hero/hero.scss

Can be observed here: https://amy.ussba.io/offices/district/6403/

TA-3334 add context to learn more button

---

src/client/components/atoms/decorative-dash/decorative-dash.jsx
src/client/components/atoms/text-input/text-input.jsx
src/client/components/molecules/contact-card/contact-card.jsx
src/client/components/molecules/newsletter-form/newsletter-form.jsx
src/client/components/molecules/quick-links/quick-links.jsx
src/client/components/organisms/blog-category-deck/blog-category-deck.jsx
src/client/components/organisms/leadership-cards/leadership-cards.jsx
src/client/components/organisms/location-info-section/location-info-section.jsx
src/client/components/templates/blog/blog.jsx
test/jest/client/components/molecules/contact-card/contact-card.test.jsx
test/jest/client/components/organisms/document-article-lookup/__snapshots__/document-article-lookup.test.jsx.snap
test/jest/client/components/organisms/footer/__snapshots__/footer.test.jsx.snap
test/jest/client/components/organisms/leadership-cards/leadership-cards.test.js
test/jest/client/components/organisms/search-box/__snapshots__/search-box.test.jsx.snap
test/jest/client/components/organisms/success-stories/success-stories.test.js
test/jest/client/components/pages/blog-category/blog-category.test.js
test/jest/client/components/pages/blog-page/blog-page.test.js
test/jest/client/components/pages/blogs-landing/blogs-landing.test.js
test/jest/client/components/pages/person-lookup-page/__snapshots__/person-lookup-page.test.jsx.snap
test/jest/client/components/pages/search-page/__snapshots__/search-page.test.jsx.snap
test/jest/client/components/templates/district-office/district-office.test.js

Deployed to https://brian.ussba.io/offices/district/6392/

Ta 3342 newsletter form accessiblity

---

src/client/components/atoms/text-input/text-input.jsx
src/client/components/atoms/text-input/text-input.scss

for jira ticket https://us-sba.atlassian.net/browse/TA-3343
AC:
To Test:
https://avery.ussba.io/offices/district/6386/

TA-3343 made Optional text accessible

---

src/client/components/templates/district-office/district-office.jsx
src/client/components/templates/district-office/district-office.scss

Deployed to https://pat.ussba.io/offices/district/6392/

TA-3347 updated styling for find more events button

---

src/client/components/templates/district-office/district-office.jsx
src/client/components/templates/district-office/district-office.scss

Can be viewed on https://amy.ussba.io/offices/district/6403/

TA-3349 add accessibility text to lender match button

---

src/client/components/templates/district-office/district-office.jsx
src/client/components/templates/district-office/district-office.scss

Deployed to [https://pat.ussba.io/offices/district/6386/](https://pat.ussba.io/offices/district/6386/).
Compare against https://mint.ussba.io/offices/district/6394/ for visual similarity

TA-3348 updated styling for lender match

---

src/client/components/atoms/image-section/image-section.jsx
src/client/components/templates/person/person.jsx
test/jest/client/components/templates/person/__snapshots__/person.test.jsx.snap
test/jest/client/components/templates/person/person.test.jsx

Deployed to https://pat.ussba.io/person/william-manger/
Test on IE 11 using either windows or Saucelabs

TA-3180 set image to use image section for person biographies

---

src/client/components/molecules/author-card/author-card.jsx

Deployed https://pat.ussba.io/offices/district/6430/

TA-3397 leadership card error with empty bio

---

src/client/components/organisms/header-footer/footer/footer.jsx
test/jest/client/components/organisms/footer/__snapshots__/footer.test.jsx.snap

Deployed to https://pat.ussba.io/
Check in both mobile and desktop view. 
For https://us-sba.atlassian.net/browse/TA-3457

TA-3457 updated footer

---

package.json
src/client/components/templates/district-office/district-office.jsx
test/jest/client/components/templates/district-office/district-office.test.js

See at https://pat.ussba.io/offices/district/6430/

TA-3466 removed events from office pages and adjusted tests

---

src/client/components/organisms/document-article/document-article.jsx

All info:
https://pat.ussba.io/article/2019/jun/27/sbrea-online-notice
Name & email:
https://pat.ussba.io/article/2019/oct/17/testimony-inspector-general-mike-hannibal-ware-house-committee-small-business
Name & phone:
https://pat.ussba.io/article/2019/aug/22/scelerisque-eleifend-donec-pretium-vulputate
No contact info:
https://pat.ussba.io/article/2014/oct/03/manufacturing-day

TA-3455 add name to contact section

---

src/client/components/organisms/document-article/document-article.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-3453
AC:

TA-3453 added subtitle to document article component

---

src/client/components/molecules/author-card/author-card.jsx
src/client/components/templates/district-office/district-office.jsx
test/jest/client/components/molecules/author-card/author-card.test.jsx
test/jest/client/components/templates/district-office/district-office.test.js

Can be observed here: http://amy.ussba.io/offices/district/26624/

TA-3508 modify leadership section on DO page

---

src/client/components/organisms/document-article/document-article.jsx
src/client/components/pages/article-page/article-page.jsx
src/client/components/pages/root-page.jsx

sample article without: https://amy.ussba.io/article/2020/feb/07/sed-do-eiusmod-tempor-incididunt-ut-labore
sample article with media contact: https://amy.ussba.io/article/2020/jan/28/test-article-page-mjackson-test

TA-3528 article data partial refactor

---

src/client/components/pages/event-page/event-page.jsx
src/client/components/pages/root-page.jsx
src/client/components/routes.jsx
src/service/url-redirect.js
test/jest/client/components/pages/event-page/event-page.test.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-3540
AC:
For Testing:
Please visit https://avery.ussba.io/events/304

TAS-3540 added event page route

---

src/client/components/organisms/event-result/event-result.jsx

Can be checked out by clicking an event from: 
- the event search page  https://amy.ussba.io/events/find/
- events section on district office page https://amy.ussba.io/offices/district/6386/

TA-3563 change individual event url

---

src/client/components/templates/event/event.jsx
src/client/components/templates/event/event.scss
test/jest/client/components/templates/event/event.test.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-3570
AC:

TA-3570 added 'Canceled' ui element and test

---

src/client/components/molecules/main-loader/main-loader.jsx
src/client/components/templates/program-page/program-page.jsx

Can be tested in avery's environment here: https://avery.ussba.io/business-guide/grow-your-business/international-sales

TA-3559 handle loader display

---

src/client/components/templates/event/event.jsx
test/jest/client/components/templates/event/event.test.jsx
test/jest/client/components/test-data/events.json

Updated in amy's environment. 
Example recurring event found here: https://amy.ussba.io/events/123456789

TA-3569 update recurring info for event

---

src/client/components/pages/event-page/event-page.jsx
src/client/components/templates/eventD7/event.jsx
src/client/components/templates/eventD7/event.scss

Compare environments
avery is pointing to D7 for events: https://avery.ussba.io/events/1638437
amy is pointing to D8 for events: https://amy.ussba.io/events/123456789

TA-3569 add flag for D7 events for recurring event info

---

src/client/components/molecules/contact-card/contact-card.jsx
src/client/components/organisms/index.jsx
src/client/components/organisms/lender-detail/lender-detail.jsx
src/client/components/organisms/lender-detail/lender-detail.scss
src/client/components/organisms/lender-result/lender-result.jsx
src/client/components/organisms/lender-result/lender-result.scss
src/client/components/organisms/primary-search-bar/primary-search-bar.jsx
src/client/components/organisms/primary-search-bar/primary-search-bar.scss
src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
src/client/components/routes.jsx
src/client/components/templates/search/search.jsx

https://amy.ussba.io/lender-lookup/find/

TA-3627-paycheck-protection-program

---

src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-3632
AC:

Feature ta 3632

---

src/client/components/routes.jsx
src/client/components/templates/event/event.jsx
src/server.js

https://amy.ussba.io/events/336
https://amy.ussba.io/events/298
Changes are also deployed to avery's environment, to show there are no regression issues for environments pointed to D7 for events: https://avery.ussba.io/events/1646354

TA-2662 event meta data

---

src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

TC-4 increase lender search result pagination to 20

---

src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx

Request to update the text and subtext

update text and subtext

---

test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

Adds jest tests to lender lookup page

Add code coverage to lender lookup page

---

src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

Add call to action for additional relief sources

---

src/client/components/molecules/contact-card/contact-card.jsx
src/client/components/molecules/index.jsx
src/client/components/molecules/lender-result-card/lender-result-card.jsx
src/client/components/molecules/lender-result-card/lender-result-card.scss
src/client/components/organisms/lender-detail/lender-detail.jsx
src/client/components/organisms/office-map/office-map.scss
src/client/components/organisms/results/results.jsx
src/client/components/organisms/results/results.scss
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
test/jest/client/components/molecules/lender-result-card/lender-result-card.test.jsx

TC-66 UI updates to lender results list

---

src/client/components/molecules/lender-result-card/lender-result-card.jsx
src/client/components/molecules/lender-result-card/lender-result-card.scss
src/client/components/organisms/lender-detail/lender-detail.jsx
src/client/components/organisms/results/results.scss
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
src/client/components/pages/office-lookup-page/office-lookup-page.scss
test/jest/client/components/molecules/lender-result-card/lender-result-card.test.jsx

TC-66 Add scroll bar to lender results

---

src/client/components/molecules/card/card.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
test/jest/client/components/organisms/program-details-card-collection/__snapshots__/program-details-card-collection.test.js.snap
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

Adds info section at the top of lender search

TC-6 information checklist

---

src/client/components/pages/document-page/document-page.jsx
src/client/components/pages/root-page.jsx
src/client/components/templates/document-article/document-article.jsx
test/jest/client/components/pages/document-page/document-page.test.jsx

For: https://us-sba.atlassian.net/browse/TA-3548

TA-3548 Refactor document-page.jsx 'fetchDocument' to use node id directly

---

src/client/components/organisms/paging-lookup/paging-lookup.jsx

Addresses this: https://us-sba.atlassian.net/browse/TA-2853

TA-2853 Fix triplicate requests happening on document search submit

---

package.json
src/client/components/app.jsx
src/client/components/atoms/carousel/carousel.jsx
src/client/components/atoms/carousel/styles.scss
src/client/components/atoms/index.js
src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
test/jest/client/components/atoms/carousel/carousel.test.jsx
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx
webpack.config.shared.js

- Integrates `react-responsive-carousel` into a reusable component
- Adds top banner carousel to lender lookup page
- Removes old unused carousel
- Adds tests

TC-7 Carousel

---

src/client/components/atoms/text-section/text-section.jsx
test/jest/client/components/atoms/text-section/__snapshots__/text-section.test.jsx.snap

https://us-sba.atlassian.net/browse/TA-3674

TA-3674 render arabic script right-to-leftt

---

src/client/components/atoms/text-input/text-input.jsx
src/client/components/organisms/primary-search-bar/primary-search-bar.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
test/jest/client/components/atoms/text-input/text-input.test.js
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

This pull request adds a find a lender search box. It allows users to narrow their zipcode search by lender name as well.

Lender search filter - FE

---

src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx

This pull request sets optional flag to true for the Lender search text field.

pass optional for lender name

---

src/client/components/pages/file-transfer-service-page/file-transfer-service-page.jsx

https://us-sba.atlassian.net/browse/TA-3594

TA-3594 enable text area input for file upload message

---

src/client/components/atoms/text-input/text-input.jsx
src/client/components/pages/file-transfer-service-page/file-transfer-service-page.jsx
test/jest/client/components/pages/file-transfer-service-page.jsx/file-transfer-service-page.test.jsx

https://us-sba.atlassian.net/browse/TA-3686

TA-3686 send button

---

src/client/components/atoms/datalist-dropdown/datalist-dropdown.jsx
src/client/components/atoms/index.js
src/client/components/atoms/text-input/text-input.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
test/jest/client/components/organisms/document-article-lookup/__snapshots__/document-article-lookup.test.jsx.snap
test/jest/client/components/organisms/search-box/__snapshots__/search-box.test.jsx.snap
test/jest/client/components/pages/person-lookup-page/__snapshots__/person-lookup-page.test.jsx.snap
test/jest/client/components/pages/search-page/__snapshots__/search-page.test.jsx.snap

Introduces a new datalist component
Hooks up the front end to the suggester backend

TA-3629 Autocomplete lender

---

src/client/components/pages/file-transfer-service-page/file-transfer-service-page.jsx

https://us-sba.atlassian.net/browse/TA-3712

TA-3712 add folder name to data to be submitted, with timestamp

---

src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

TC- 141
Removes carousel
Removes info section on mobile

TC-141 UI changes

---

.eslintrc.json
src/client/components/pages/file-transfer-service-page/file-transfer-service-page.jsx
src/client/components/pages/file-transfer-service-page/file-transfer-service-page.scss

Implements some user feedback and error handling.
https://us-sba.atlassian.net/browse/TA-3707

TA-3707  loan processing form submission validation/error handling

---

src/client/components/pages/file-transfer-service-page/file-transfer-service-page.jsx
src/server.js

for jira ticket https://us-sba.atlassian.net/browse/TA-3687
AC:

Feature ta 3687

---

src/client/components/molecules/breadcrumb/breadcrumb.jsx

https://us-sba.atlassian.net/browse/TA-3740
Acceptance Criteria: 
Update the link for the home icon

TA-3740 fix breadcrumbs home link

---

src/client/components/pages/error-page/error-page.jsx

This pull request removes the red line that shows up in the 404 page.

TC-194 - remove red line in 404 page

---

config/test.yml

`config/test.yml` is not being used, so it was removed.

TA-3620 Remove config/test.yml

---

src/client/components/pages/break-even-calc-landing-page/break-even-calc-landing-page.jsx
src/client/components/pages/break-even-calc-landing-page/break-even-calc-landing-page.scss
src/client/components/pages/break-even-calc-landing-page/content.js

Content changes for the landing page.

update calculator content

---

src/client/components/molecules/title-section/title-section.jsx
src/client/components/organisms/developer-tester/developer-tester.jsx
src/client/components/organisms/header-footer/header/header.jsx

Removing a couple unused Redux imports

TA-3509 Remove Redux, Part 1

---

src/client/components/organisms/news-releases/news-releases.jsx
test/jest/client/components/organisms/news-releases/news-releases.test.js

Can be seen here: http://amy.ussba.io/offices/district/6394/

TA-3848 remove article category from api calls

---

src/client/components/molecules/detail-card/detail-card.jsx
src/client/components/molecules/detail-card/detail-card.scss
src/client/components/organisms/detail-card-collection/detail-card-collection.jsx
src/client/components/organisms/news-releases/news-releases.jsx
test/jest/client/components/organisms/document-article-lookup/__snapshots__/document-article-lookup.test.jsx.snap
test/jest/client/components/organisms/news-releases/news-releases.test.js

for jira tickets https://us-sba.atlassian.net/browse/TA-3850
AC:
Can be tested here: https://avery.ussba.io/offices/district/6394/

TA-3850 added date data

---

src/client/components/molecules/card/card.jsx
src/client/components/organisms/success-stories/success-stories.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-3900
AC:

TA-3900 removed read full post

---

src/client/components/molecules/newsletter-form/newsletter-form.scss

for jira ticket https://us-sba.atlassian.net/browse/TA-3845
AC:
Can be tested here https://avery.ussba.io/

TA-3845 fixed tablet breakpoint social media link issue

---

src/client/components/pages/break-even-calc-landing-page/break-even-calc-landing-page.jsx
src/client/components/pages/break-even-calc-landing-page/break-even-calc-landing-page.scss

TC-143 Add breadcrumbs to landing page

---

src/client/components/molecules/card/card.jsx
src/client/components/organisms/success-stories/success-stories.scss
test/jest/client/components/molecules/card/__snapshots__/card.test.jsx.snap
test/jest/client/components/organisms/courses-layout/__snapshots__/courses-layout.test.jsx.snap

https://us-sba.atlassian.net/browse/TA-3902
Example with summaries that fit the character limit:
https://pat.ussba.io/offices/district/6393/
Example with summaries that exceed the character limit:
https://pat.ussba.io/offices/district/6390/

TA-3902 Add caret link to end of DO success stories summary

---

src/client/components/organisms/sbic-lookup/sbic-lookup.jsx
src/client/components/organisms/sbic-lookup/sbic-lookup.scss

for jira ticket https://us-sba.atlassian.net/browse/TA-2182
Actual Result:
The correct table head layout can be viewed here: http://avery.ussba.io/funding-programs/investment-capital

TA-2182 corrected table head alignment issues

---

src/client/components/atoms/back-to-top-button/back-to-top-button.jsx
src/client/components/atoms/back-to-top-button/back-to-top-button.module.scss
src/client/components/atoms/index.js
src/client/components/organisms/header-footer/footer/footer.jsx
test/jest/client/components/atoms/back-to-top-button/back-to-top-button.test.jsx
test/jest/client/components/organisms/footer/__snapshots__/footer.test.jsx.snap
test/jest/client/components/organisms/footer/footer.test.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-3827
AC:
You can this this code at: https://avery.ussba.io/ and scroll down. I set the threshold to `600` pixels. This can be adjusted as desired by the UX team.

Feature ta 3827

---

src/client/components/routes.jsx

This pull request changes the routs from breakevencalculator to breakevenpointcalculator so that the url will include the word "point" in it.

TC-343 - change BEPC route name

---

src/client/components/pages/break-even-calc-landing-page/break-even-calc-landing-page.jsx

This pull request does the following:
- adds link to the 'Start Analysis' button
- fixes some warning messages for lists that did not have keys
- merges recent code from master

TC-343 - add analyze link and fix key warning message

---

src/client/components/organisms/sbic-lookup/sbic-lookup.jsx
src/client/components/organisms/sbic-lookup/sbic-lookup.scss
src/client/services/us-states.json

https://us-sba.atlassian.net/secure/RapidBoard.jspa?rapidView=1&modal=detail&selectedIssue=TA-3832

TA-3832 Add states filtering option to sbic directory

---

src/client/components/pages/break-even-calc-landing-page/accordion.scss
src/client/components/pages/break-even-calc-landing-page/break-even-calc-landing-page.jsx
src/client/components/pages/break-even-calc-landing-page/break-even-calc-landing-page.scss

Adjust styles for mobile. 
Replace gradient background.
Make subheadings into h3

TC-388 & TC-441 Landing Page Mobile + 508

---

src/client/components/pages/break-even-calc-landing-page/break-even-calc-landing-page.jsx

This pull request does the following:
- Updates the landing page verbiage
https://docs.google.com/document/d/1kkU1DiQFuXgadi1RUVWY8grKhfnP3rlX4BeMZWxJLqY/edit

TC-462 - update landing page verbiage

---

src/client/components/organisms/sbic-lookup/sbic-lookup.jsx
src/client/components/organisms/sbic-lookup/sbic-lookup.scss

Style updates to handle text overlap.
In mobile, view the SBIC table on this page http://amy.ussba.io/funding-programs/investment-capital
Comparison: https://www.sba.gov/funding-programs/investment-capital

TA-2183 sbic mobile display

---

config/brian.yml
config/default.yaml
config/mint.yml
config/production.yml
config/ryan.yml
src/server.js

This pull request adds a feature flag so that breakevenpointcalculator can be disabled on prod so it remains hidden till ready.

add feature flag for breakevenpointcalculator

---

config/production.yml

This pull request sets the breakEvenCalculator feature flag to true so that it can show up on production

update feature flag for bepc on production to be true

---

src/client/components/pages/break-even-calc-landing-page/break-even-calc-landing-page.jsx

This pull request updates the start link to work properly with the new infrastructure update.

update landing link

---

.circleci/config.yml
src/client/components/organisms/office-result/office-result.jsx
src/client/components/organisms/office-result/office-result.scss
test/jest/client/components/organisms/office-result/office-result.test.jsx

Use PhoneNumber component
Add test for changes

TC-744 Make phone number clickable

---

src/client/components/pages/office-lookup-page/office-lookup-page.jsx

This pull request cleans up one line of code that noticed is not necessary.

remove this.setState from the if condition in local assist code since it is being set after

---

src/client/components/atoms/text-section/text-section.jsx
src/client/components/atoms/text-section/text-section.scss

Changes are currently live on Venus.

TA-4233- Support mobile tables with th rows

---

src/client/components/organisms/office-result/office-result.scss

This pull request cleans up the mobile result styling so that h tags are styled the same in mobile and desktop the same.

TC-743 - update mobile result list styling

---

src/client/components/atoms/multiselect/taxonomy-multiselect.jsx
src/client/components/pages/office-lookup-page/office-lookup-page.jsx
src/client/components/templates/search/search.jsx
test/jest/client/components/atoms/multiselect/taxonomy-multiselect.test.js

Search only the offices listed in dropdown when 'all' option is selected

TC-805 Adjust All offices option

---

src/client/components/atoms/datalist-dropdown/datalist-dropdown.jsx
src/client/components/atoms/multiselect/multiselect.jsx
src/client/components/atoms/multiselect/multiselect.scss
src/client/components/atoms/multiselect/taxonomy-multiselect.jsx
src/client/components/pages/office-lookup-page/office-lookup-page.jsx
src/client/components/templates/search/search.jsx
test/jest/client/components/atoms/multiselect/taxonomy-multiselect.test.js

TC-804 dropdown height

---

src/client/components/organisms/office-map/office-map.jsx
src/client/components/organisms/office-map/office-map.scss
src/client/components/organisms/results/results.jsx
src/client/components/pages/office-lookup-page/office-lookup-page.jsx

Max out at 50 pages, 5 results per page

TC-740 Return fewer  local assistance results 

---

src/client/components/templates/search/search.jsx

This pull request fixes the issue with  district office showing before results or results displaying to district offices.

changes made to fix district office bug

---

src/client/components/organisms/office-result/office-result.jsx
src/client/components/organisms/office-result/office-result.scss
src/client/components/templates/search/search.jsx
src/client/styles/base/_variables.scss

This pull request styles the district office so it stands out from the rest of the result list.

TC-817 - Styling for district office in results list

---

src/client/components/atoms/button/button.jsx
src/client/components/atoms/button/button.scss
src/client/components/organisms/primary-search-bar/primary-search-bar.jsx
src/client/components/organisms/primary-search-bar/primary-search-bar.scss
src/client/components/pages/office-lookup-page/office-lookup-page.jsx
src/client/components/pages/office-lookup-page/office-lookup-page.scss
test/jest/client/components/organisms/primary-search-bar/primary-search-bar.test.js

Add info button to primary search bar. Toggle text on click.

TC-739 info button

---

src/client/components/organisms/results/results.jsx
src/client/components/pages/office-lookup-page/office-lookup-page.jsx
src/client/components/pages/office-lookup-page/office-lookup-page.scss
src/client/components/templates/search/search.jsx
test/jest/client/components/organisms/results/results.test.js

TC-833 Filter out offices farther than 500 miles away from zipcode

---

src/client/components/templates/search/search.jsx

This pull request fixes the bug where when you drag the map the distance can still be calculated with Long and Lat.

TC-861 - Handle Distance Error

---

src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss

Removes the gap between that map and results on find a lender page

TC-823 Remove Gap on PPP page

---

src/client/components/pages/office-lookup-page/office-lookup-page.scss

TC-880 Make error message 508 compliant

---

.circleci/config.yml

Sorry for the whitespace stuff, it was autocorrected in my IDE. Check line 259 for changes

CircleCi fix for building

---

src/client/components/atoms/checkbox/checkbox-lib.jsx
src/client/components/atoms/multiselect/multiselect.jsx
src/client/components/atoms/text-input/text-input.jsx
src/client/components/atoms/textarea/textarea.jsx
src/client/components/molecules/office-contact-modal/office-contact-modal.jsx
src/client/components/organisms/office-result/office-result.jsx
src/client/components/pages/office-lookup-page/office-lookup-page.jsx
src/client/components/templates/search/search.jsx

- DO Form National Release
- DO Form Accessibility Tweaks 
- Fixes for react-specific errors that were appearing in console

Mdeeb/tb-831 
