src/client/components/atoms/text-section/text-section.jsx

Can currently be observed in amy.ussba.io
Example of basic page with .gov link, relative link, and external non-.gov link (accredited registrars link near bottom of page):
https://amy.ussba.io/business-guide/launch-your-business/choose-your-business-name

TA-2491 modify regex to handle more links

---

src/client/components/atoms/text-section/text-section.scss

Can be viewed in amy.ussba.io on any basic page.
Example of page with external link that now matches color of internal links: http://amy.ussba.io/business-guide/launch-your-business/choose-your-business-name and go near bottom of the page to view `accredited registrars` link.

TA-2486 add styles for link color in text section

---

src/client/components/molecules/quick-links/quick-links.jsx
test/jest/client/components/molecules/quick-links/__snapshots__/quick-links.test.js.snap
test/jest/client/components/molecules/quick-links/quick-links.test.js

for jira ticket https://us-sba.atlassian.net/browse/TA-2922

TA-2922 added no-results state and unit test

---

src/client/components/pages/blog-category/blog-category-page.jsx
test/jest/client/components/pages/blog-category/blog-category.test.js

Example: https://amy.ussba.io/blogs/success-stories/19527/
Note: Needed to update existing tests in the blog category test suite to scope portions within setImmediate blocks

TA-3005 use featured image for posts on blog category page

---

src/client/components/atoms/card-container/card-container.jsx
src/client/components/organisms/generic-card-collection/generic-card-collection.jsx

Changes are updated in amy's environment.
Compare axe id errors for location info cards in mint versus resolved errors in amy.
https://amy.ussba.io/offices/district/6472/
https://mint.ussba.io/offices/district/19586/
Errors seen in mint:
- IDs of active elements must be unique
- id attribute value must be unique

TA-3298 remove unnecessary ids

---

src/client/components/molecules/quick-links/quick-links.jsx
src/client/components/molecules/quick-links/quick-links.scss
test/jest/client/components/molecules/quick-links/__snapshots__/quick-links.test.js.snap

For the purposes of accessibility, the header of the quick links component has been changed to use a `p` tag instead of an `h4` and then added styling to make sure that the `p` tag displays the same.
Updated on Document List which can be seen at the bottom of the district office page:
https://amy.ussba.io/offices/district/6403/
Updated on Article List and Rates List which can be seen at the bottom of this page: http://localhost:3000/business-guide/plan-your-business/market-research-competitive-analysis

TA-3350 change header to p tag; add styling; update snapshots

---

src/client/components/molecules/quick-links/quick-links.jsx
test/jest/client/components/molecules/quick-links/__snapshots__/quick-links.test.js.snap

Deployed to https://pat.ussba.io/offices/district/6386/
Use screen reader to hear that "See All" button is labeled with "See all documents"

TA-3351 updated quick links to have aria label with see all link

---

src/client/components/organisms/news-releases/news-releases.jsx
src/client/components/templates/district-office/district-office.jsx
test/jest/client/components/organisms/news-releases/news-releases.test.js
test/jest/client/components/test-data/news-releases/oneNewsReleasesData.json
test/jest/client/components/test-data/news-releases/threeNewsReleasesData.json

Can be observed here:
https://amy.ussba.io/offices/district/20353/ (no region specified for office)
https://amy.ussba.io/offices/district/20355/ (this office has a region that we will see in the article request)
Note that we will always see `national=true` in the query

TA-3294 update news releases query params

---

src/client/components/pages/blogs-landing/blogs-landing.jsx

Updated on https://amy.ussba.io/blogs/
Authors should always display in the order the following order:
```
[18235,18210,7766,18220,18218,18219]
18235 Chris Pilkerton
18210 William Manger
7766 Larry Stubblefield
18220 Kathleen McShane
18218 Michele Schimpp
18219 Allen Gutierrez
```
Compare to https://mint.ussba.io/blogs/ where ordering of authors is not consistent.

TA-3434 preserve order of authors on blogs landing page

---

src/client/components/molecules/district-office-previous-next/district-office-previous-next.jsx
src/client/components/molecules/index.jsx
src/client/components/organisms/district-office-section-nav/district-office-section-nav.jsx
src/client/components/organisms/index.jsx
src/client/components/routes.jsx
src/client/components/templates/district-office-subpage/district-office-subpage.jsx
test/jest/client/components/templates/district-office-subpage/district-office-subpage.test.js

for jira ticket https://us-sba.atlassian.net/browse/TA-3314
To Do:
To Test, visit:
https://avery.ussba.io/offices/district/6386/20243

TA-3314 created subpage navigation and unit tests

---

src/client/components/pages/sitemap-page/sitemap-page.jsx
src/client/components/pages/sitemap-page/sitemap-page.scss
src/client/components/routes.jsx
test/jest/client/components/pages/sitemap-page/sitemap-page.test.js

for jira ticket https://us-sba.atlassian.net/browse/TA-3519
Page is created in Katana to display sitemap list with URL links

Feature ta 3519

---

config/avery.yml
src/client/components/pages/event-page/event-page.jsx
test/jest/client/components/pages/event-page/event-page.test.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-3614
AC:
Before, now matter what event was clicked on, only the most recent event detail information displayed.
Now, any event that is clicked on from https://avery.ussba.io/events/ will open to its correct event detail information.

Feature ta 3614

---

src/client/components/molecules/contact-card/contact-card.jsx
src/client/components/organisms/lender-detail/lender-detail.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

This is to display website information in the contact card on the ppp lender map.
To see in action go to `https://pat.ussba.io/paycheckprotection/find?address=48342&hasFiled2019Taxes=true&pageNumber=1` and select the second result `Bank of America Financial Center`. You should see a link at the bottom of the lender details card that says "Website". Clicking on that should take you to the bank of america webpage. Other lenders should not have website information as of 2:30 on 4/10

TC-3 added website to lender details and contact card components

---

src/client/components/pages/event-lookup-page/event-lookup-page.jsx

Deployed to [https://pat.ussba.io/events/find](https://pat.ussba.io/events/find)
Verify that the number of results is displayed at the top of the page and the pagination displays correctly at the bottom of the page

TA-3617 fixed events pagination to use count value

---

src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

Add link to SBA District Office to the bottom of the map on lender lookup page.
Add tests to assert the presence of the right link

TC-39: Display District Office info for users to report incorrect map information.

---

src/client/components/molecules/contact-card/contact-card.jsx
src/client/components/organisms/lender-detail/lender-detail.jsx
src/client/components/organisms/lender-detail/lender-detail.scss
src/client/components/organisms/results/results.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.jsx
src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
test/jest/client/components/pages/lender-lookup-page/lender-lookup-page.test.jsx

- Surface the relevant information in lender results without requiring an extra click
- Adjust padding on banner to line up with other elements

Lender results card UI changes

---

src/client/components/molecules/lender-result-card/lender-result-card.jsx
src/client/components/molecules/lender-result-card/lender-result-card.scss
test/jest/client/components/molecules/lender-result-card/lender-result-card.test.jsx

Transform all caps city names to capital case, make all zip codes 5 digits

TC-74 Format Addresses in Search Results

---

src/client/components/organisms/sbic-lookup/sbic-lookup.jsx
src/server.js

Fixes: https://us-sba.atlassian.net/browse/TA-3802
Cloudfront directs requests to `/api/content/*` to an S3 bucket so our code to generate the CSV wasn't being used. Instead, it's likely the download button only worked before this because the CSV was manually entered into that bucket (it must have been deleted from the environments this was broken in). 
We already had code to generate the CSV programmatically from the Content API, so by changing the request to hit a different url we can now actually use that code to generate the CSV download. 😄

TA-3802 Use a different path to route to the download function

---

src/client/components/organisms/news-releases/news-releases.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-3849
AC:
This change can be viewed at: https://avery.ussba.io/offices/district/6394/

TA-3849 disabled summary field

---

src/client/components/organisms/document-article/document-article.jsx

for jira ticket https://us-sba.atlassian.net/browse/TA-3539
AC:
-  [x] Articles of type Press Release should display the articles created date INSTEAD of the last updated date
-  [x] The created date message should display as follows - [Date: February 22, 2020]

TA-3539 converted last updated to authored on

---

src/client/components/pages/lender-lookup-page/lender-lookup-page.scss
src/client/components/pages/office-lookup-page/office-lookup-page.jsx
src/client/components/pages/office-lookup-page/office-lookup-page.scss

`setWhiteBackground` prop was absolutely positioning the paginator causing it to obscure the last result in the list.

TC-822 Prevent results from being cut off
